service:
  name: one

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: controller.home.handler
    events:
      - http:
          method: get
          path: hello
